# Generated by Django 5.2.18 on 2026-10-07 17:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'progress_certificate_template',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_code', models.CharField(max_length=20, unique=True)),
                ('score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='education.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='progress.certificatetemplate')),
            ],
            options={
                'db_table': 'progress_certificate',
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='progress.certificate')),
            ],
            options={
                'db_table': 'progress_certificate_verification',
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Termine')], default='in_progress', max_length=12)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='education.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_chapter_progress',
            },
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'course'), name='uniq_certificate_active'),
        ),
        migrations.AddIndex(
            model_name='certificateverification',
            index=models.Index(fields=['certificate', '-verified_at'], name='certverif_cert_idx'),
        ),
        migrations.AddIndex(
            model_name='chapterprogress',
            index=models.Index(condition=models.Q(('status', 'completed')), fields=['user', 'chapter'], name='chprogress_done_idx'),
        ),
        migrations.AddConstraint(
            model_name='chapterprogress',
            constraint=models.UniqueConstraint(fields=('user', 'chapter'), name='uniq_chapter_progress'),
        ),
        migrations.AddConstraint(
            model_name='chapterprogress',
            constraint=models.CheckConstraint(condition=models.Q(('percent__lte', 100)), name='chk_progress_percent'),
        ),
        migrations.AddConstraint(
            model_name='chapterprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), models.Q(('completed_at__isnull', False), ('percent', 100)), _connector='OR'), name='chk_progress_completed'),
        ),
    ]
