# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('is_african', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'profiles_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profiles_interest',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='privacy', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='public', max_length=14)),
                ('portfolio_visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='public', max_length=14)),
                ('default_post_visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='public', max_length=14)),
                ('default_status_visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='friends', max_length=14)),
                ('activity_visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='friends', max_length=14)),
                ('who_can_message', models.CharField(choices=[('everyone', 'Tout le monde'), ('friends', 'Amis'), ('nobody', 'Personne')], default='everyone', max_length=10)),
                ('who_can_send_friend_request', models.CharField(choices=[('everyone', 'Tout le monde'), ('friends', 'Amis'), ('nobody', 'Personne')], default='everyone', max_length=10)),
                ('show_presence', models.BooleanField(default=True)),
                ('show_read_receipts', models.BooleanField(default=True)),
                ('searchable', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'profiles_privacy',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'profiles_profession',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('language', 'Langage'), ('framework', 'Framework / librairie'), ('tool', 'Outil / plateforme'), ('domain', 'Domaine (ML, DevOps...)'), ('soft', 'Transversale')], default='tool', max_length=12)),
                ('is_technology', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profiles_skill',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='skill_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(default='fr', max_length=8)),
                ('time_zone', models.CharField(default='Africa/Douala', max_length=64)),
                ('theme', models.CharField(default='system', max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'profiles_preferences',
                'constraints': [models.CheckConstraint(condition=models.Q(('theme__in', ['system', 'light', 'dark'])), name='chk_pref_theme')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(max_length=80)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('avatar_key', models.CharField(blank=True, max_length=300)),
                ('cover_key', models.CharField(blank=True, max_length=300)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, size=None)),
                ('availability', models.CharField(choices=[('none', 'Non precise'), ('open_to_work', 'Ouvert aux opportunites'), ('freelance', 'Disponible en freelance'), ('hiring', 'Recrute')], default='none', max_length=14)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.country')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.profession')),
            ],
            options={
                'db_table': 'profiles_profile',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['display_name'], name='profile_name_trgm', opclasses=['gin_trgm_ops']), models.Index(fields=['country', 'availability'], name='profile_country_avail_idx'), django.contrib.postgres.indexes.GinIndex(fields=['languages'], name='profile_languages_gin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('display_name', ''), _negated=True), name='chk_profile_display_name_nonempty'), models.CheckConstraint(condition=models.Q(('is_verified', False), ('verified_at__isnull', False), _connector='OR'), name='chk_profile_verified_dated')],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('x', 'X'), ('website', 'Site web'), ('portfolio', 'Portfolio')], max_length=12)),
                ('url', models.URLField(max_length=300)),
                ('handle', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_social_link',
                'indexes': [models.Index(fields=['user'], name='sociallink_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'url'), name='uniq_sociallink')],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='profiles.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_user_interest',
                'indexes': [models.Index(fields=['interest'], name='userinterest_interest_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'interest'), name='uniq_userinterest')],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='profiles.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_user_skill',
                'indexes': [models.Index(fields=['skill', 'level'], name='userskill_skill_level_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='uniq_userskill'), models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 5)), name='chk_userskill_level'), models.CheckConstraint(condition=models.Q(('years_experience__isnull', True), ('years_experience__gte', 0), _connector='OR'), name='chk_userskill_years')],
            },
        ),
    ]
