# Generated by Django 5.2.18 on 2026-10-08 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('verify_email', 'Confirmation du compte'), ('reset_password', 'Mot de passe oublie')], max_length=16)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('emailed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts_email_otp',
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='otp_lookup_idx'), models.Index(condition=models.Q(('emailed', True)), fields=['created_at'], name='otp_emailed_day_idx')],
            },
        ),
    ]
