# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('direct', 'Message direct'), ('group', 'Conversation de groupe'), ('channel', 'Conversation de channel'), ('support', 'Support'), ('classroom', 'Classroom'), ('organization', 'Organisation')], max_length=14)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('classroom_ref', models.UUIDField(blank=True, null=True)),
                ('organization_ref', models.UUIDField(blank=True, null=True)),
                ('direct_key', models.CharField(blank=True, max_length=73, null=True)),
                ('message_seq', models.BigIntegerField(default=0, editable=False)),
                ('last_message_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='community.channel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='community.group')),
            ],
            options={
                'db_table': 'messaging_conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Membre'), ('admin', 'Administrateur')], default='member', max_length=8)),
                ('last_delivered_seq', models.BigIntegerField(default=0)),
                ('last_read_seq', models.BigIntegerField(default=0)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_conversation_member',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=255)),
                ('seq', models.BigIntegerField(default=0, editable=False)),
                ('kind', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'Fichier'), ('code', 'Code'), ('system', 'Systeme')], default='text', max_length=8)),
                ('body', models.TextField(blank=True, max_length=10000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reply_count', models.PositiveIntegerField(default=0, editable=False)),
                ('last_reply_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('client_msg_id', models.UUIDField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_message',
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_mentions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_mention',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=400)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_attachment',
            },
        ),
        migrations.CreateModel(
            name='MessageDeletion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_deletion',
            },
        ),
        migrations.CreateModel(
            name='MessageEditHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_body', models.TextField()),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='messaging.message')),
            ],
            options={
                'db_table': 'messaging_edit_history',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_reaction',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='conversation_last_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(condition=models.Q(('group__isnull', False)), fields=['group'], name='conversation_group_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(condition=models.Q(('classroom_ref__isnull', False)), fields=['classroom_ref'], name='conversation_classroom_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('direct_key',), name='uniq_conversation_direct_key'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direct_key__isnull', False), ('type', 'direct')), models.Q(models.Q(('type', 'direct'), _negated=True), ('direct_key__isnull', True)), _connector='OR'), name='chk_conversation_direct_key'),
        ),
        migrations.AddIndex(
            model_name='conversationmember',
            index=models.Index(condition=models.Q(('left_at__isnull', True)), fields=['user', 'conversation'], name='convmember_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_conversation_member'),
        ),
        migrations.AddConstraint(
            model_name='conversationmember',
            constraint=models.CheckConstraint(condition=models.Q(('last_delivered_seq__gte', 0), ('last_read_seq__gte', 0)), name='chk_convmember_seq_nonneg'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-seq'], name='message_conv_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('thread_root__isnull', False)), fields=['thread_root', 'seq'], name='message_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='message_sender_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'seq'), name='uniq_message_conv_seq'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_msg_id__isnull', False)), fields=('conversation', 'sender', 'client_msg_id'), name='uniq_message_client_id'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'text'), _negated=True), models.Q(('body', ''), _negated=True), _connector='OR'), name='chk_message_text_nonempty'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='mention_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('message', 'mentioned_user'), name='uniq_message_mention'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='attachment_message_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageattachment',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='chk_attachment_size'),
        ),
        migrations.AddConstraint(
            model_name='messagedeletion',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_message_hidden'),
        ),
        migrations.AddIndex(
            model_name='messageedithistory',
            index=models.Index(fields=['message', 'edited_at'], name='msgedit_message_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='uniq_message_reaction'),
        ),
    ]
