# Generated by Django 5.2.18 on 2026-10-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='message_conv_seq_idx',
        ),
    ]
