# Generated by Django 5.2.18 on 2026-10-07 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('size_range', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('logo_key', models.CharField(blank=True, max_length=300)),
                ('cover_key', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Non verifiee'), ('verified', 'Verifiee'), ('suspended', 'Suspendue')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.country')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies_company',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietaire'), ('admin', 'Administrateur'), ('recruiter', 'Recruteur'), ('editor', 'Editeur'), ('employee', 'Employe')], default='employee', max_length=10)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies_member',
            },
        ),
        migrations.CreateModel(
            name='CompanyProductRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_ref', models.UUIDField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_refs', to='companies.company')),
            ],
            options={
                'db_table': 'companies_product_ref',
            },
        ),
        migrations.CreateModel(
            name='CompanyProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('skills', models.ManyToManyField(blank=True, db_table='companies_project_skill', related_name='+', to='profiles.skill')),
            ],
            options={
                'db_table': 'companies_project',
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('starting_price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='companies.company')),
            ],
            options={
                'db_table': 'companies_service',
            },
        ),
        migrations.CreateModel(
            name='CompanySocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=12)),
                ('url', models.URLField(max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='companies.company')),
            ],
            options={
                'db_table': 'companies_social_link',
            },
        ),
        migrations.CreateModel(
            name='CompanyVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('domain_email', 'E-mail du domaine'), ('document', 'Document officiel'), ('manual', 'Verification manuelle')], max_length=14)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvee'), ('rejected', 'Rejetee')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='companies.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies_verification',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['country', 'status'], name='company_browse_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('size_range__in', ['', '1-10', '11-50', '51-200', '201-1000', '1000+'])), name='chk_company_size'),
        ),
        migrations.AddIndex(
            model_name='companymember',
            index=models.Index(fields=['user'], name='companymember_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_member'),
        ),
        migrations.AddConstraint(
            model_name='companyproductref',
            constraint=models.UniqueConstraint(fields=('company', 'product_ref'), name='uniq_company_productref'),
        ),
        migrations.AddConstraint(
            model_name='companyservice',
            constraint=models.CheckConstraint(condition=models.Q(('starting_price_minor__isnull', True), models.Q(('currency', ''), _negated=True), _connector='OR'), name='chk_companyservice_currency'),
        ),
        migrations.AddConstraint(
            model_name='companysociallink',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'url'), name='uniq_company_social'),
        ),
        migrations.AddConstraint(
            model_name='companysociallink',
            constraint=models.CheckConstraint(condition=models.Q(('url__startswith', 'https://')), name='chk_company_social_https'),
        ),
        migrations.AddConstraint(
            model_name='companyverification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company',), name='uniq_verification_pending'),
        ),
        migrations.AddConstraint(
            model_name='companyverification',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'pending'), ('reviewed_at__isnull', False), _connector='OR'), name='chk_verification_reviewed'),
        ),
    ]
