# Generated by Django 5.2.18 on 2026-10-07 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'job categories',
                'db_table': 'jobs_category',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jobs_job_skill',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('due_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'A faire'), ('in_progress', 'En cours'), ('submitted', 'Livre'), ('approved', 'Valide')], default='pending', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs_milestone',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('period', models.CharField(default='month', max_length=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Envoyee'), ('accepted', 'Acceptee'), ('declined', 'Refusee'), ('withdrawn', 'Retiree')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs_offer',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(max_length=10000)),
                ('bid_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('delivery_days', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Envoyee'), ('accepted', 'Acceptee'), ('rejected', 'Refusee'), ('withdrawn', 'Retiree')], default='submitted', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'jobs_proposal',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_application_status_event',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('employment', 'Emploi'), ('freelance', 'Freelance')], max_length=10)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'En cours'), ('completed', 'Termine'), ('terminated', 'Resilie')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_client', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_contractor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_contract',
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='freelancer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('hourly_rate_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'jobs_freelancer_profile',
                'indexes': [models.Index(condition=models.Q(('is_available', True)), fields=['hourly_rate_minor'], name='freelancer_available_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hourly_rate_minor__isnull', True), models.Q(('currency', ''), _negated=True), _connector='OR'), name='chk_freelancer_currency')],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_interview_slot',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('video', 'Visio'), ('phone', 'Telephone'), ('onsite', 'Sur site')], default='video', max_length=8)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('scheduled', 'Planifie'), ('completed', 'Termine'), ('cancelled', 'Annule'), ('no_show', 'Absent')], default='scheduled', max_length=10)),
                ('feedback', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview', to='jobs.interviewslot')),
            ],
            options={
                'db_table': 'jobs_interview',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=20000)),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('internship', 'Stage'), ('contract', 'Mission'), ('freelance', 'Freelance (projet)')], max_length=12)),
                ('contract_type', models.CharField(choices=[('permanent', 'CDI'), ('fixed_term', 'CDD'), ('freelance', 'Freelance'), ('internship', 'Stage')], max_length=12)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Confirme'), ('senior', 'Senior'), ('lead', 'Lead / Principal')], default='mid', max_length=8)),
                ('remote_policy', models.CharField(choices=[('onsite', 'Sur site'), ('hybrid', 'Hybride'), ('remote', 'Teletravail')], default='onsite', max_length=8)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('salary_min_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('salary_max_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=3)),
                ('salary_period', models.CharField(blank=True, max_length=6)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouverte'), ('paused', 'En pause'), ('closed', 'Fermee'), ('filled', 'Pourvue')], default='draft', max_length=8)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.country')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_job',
            },
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='jobs.job'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Envoyee'), ('reviewing', "En cours d'examen"), ('shortlisted', 'Pre-selectionnee'), ('interview', 'Entretien'), ('offer', 'Offre'), ('hired', 'Embauche'), ('rejected', 'Refusee'), ('withdrawn', 'Retiree')], default='submitted', max_length=12)),
                ('cover_letter', models.TextField(blank=True, max_length=10000)),
                ('cv_storage_key', models.CharField(blank=True, max_length=400)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('gitlab_url', models.URLField(blank=True)),
                ('links', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('expected_salary_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'jobs_application',
            },
        ),
    ]
