# Generated by Django 5.2.18 on 2026-10-07 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='projects',
            field=models.ManyToManyField(blank=True, db_table='jobs_application_project', related_name='+', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='booked_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='contract',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationstatusevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSkill', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='jobs.contract'),
        ),
        migrations.AddField(
            model_name='offer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.proposal'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status', '-created_at'], name='application_job_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', '-created_at'], name='application_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='uniq_application'),
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(condition=models.Q(('booked_by__isnull', True)), fields=['job', 'starts_at'], name='slot_free_idx'),
        ),
        migrations.AddConstraint(
            model_name='interviewslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='chk_slot_period'),
        ),
        migrations.AddIndex(
            model_name='applicationstatusevent',
            index=models.Index(fields=['application', 'created_at'], name='appstatus_app_idx'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['skill'], name='jobskill_skill_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.UniqueConstraint(fields=('job', 'skill'), name='uniq_job_skill'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['-published_at'], name='job_open_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['country', 'job_type', '-published_at'], name='job_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='job_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('salary_max_minor__isnull', True), ('salary_min_minor__isnull', True)), models.Q(('salary_max_minor__isnull', False), ('salary_min_minor__isnull', False), ('salary_min_minor__lte', models.F('salary_max_minor')), models.Q(('salary_currency', ''), _negated=True), models.Q(('salary_period', ''), _negated=True)), _connector='OR'), name='chk_job_salary'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('salary_period__in', ['', 'hour', 'day', 'month', 'year'])), name='chk_job_salary_period'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'open'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_job_open_dated'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('deadline__isnull', True), ('published_at__isnull', True), ('deadline__gt', models.F('published_at')), _connector='OR'), name='chk_job_deadline'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('contract', 'position'), name='uniq_milestone_position'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='chk_milestone_amount'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_at__isnull', False), _connector='OR'), name='chk_milestone_approved_dated'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0), models.Q(('currency', ''), _negated=True)), name='chk_offer_amount'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['sent', 'accepted'])), fields=('application',), name='uniq_offer_active'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('job', 'freelancer'), name='uniq_proposal'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('job',), name='uniq_proposal_accepted_per_job'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(('bid_minor__gt', 0), ('delivery_days__gt', 0), models.Q(('currency', ''), _negated=True)), name='chk_proposal_values'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', False), ('proposal__isnull', True)), models.Q(('application__isnull', True), ('proposal__isnull', False)), _connector='OR'), name='chk_contract_single_source'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('client', models.F('contractor')), _negated=True), name='chk_contract_distinct_parties'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='chk_contract_dates'),
        ),
    ]
