# Generated by Django 5.2.18 on 2026-10-07 03:31

import apps.core.encryption
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('repository', 'Depot'), ('profile', 'Profil'), ('post', 'Publication')], max_length=12)),
                ('canonical_url', models.URLField(max_length=600)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=600)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Disponible'), ('unavailable', 'Indisponible (supprime/prive cote fournisseur)')], default='active', max_length=12)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'integrations_content',
            },
        ),
        migrations.CreateModel(
            name='ExternalAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('handle', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('profile_url', models.URLField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'integrations_author',
            },
        ),
        migrations.CreateModel(
            name='ExternalProvider',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('supports_oauth', models.BooleanField(default=False)),
                ('supports_embed', models.BooleanField(default=False)),
                ('terms_url', models.URLField(blank=True)),
                ('max_cache_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'integrations_provider',
            },
        ),
        migrations.CreateModel(
            name='EmbedMetadata',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embed', serialize=False, to='integrations.externalcontent')),
                ('embed_url', models.URLField(max_length=700)),
                ('oembed_version', models.CharField(default='1.0', max_length=10)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integrations_embed',
            },
        ),
        migrations.CreateModel(
            name='ExternalVideo',
            fields=[
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video', serialize=False, to='integrations.externalcontent')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'integrations_video',
            },
        ),
        migrations.AddField(
            model_name='externalcontent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='integrations.externalauthor'),
        ),
        migrations.AddField(
            model_name='externalcontent',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='integrations.externalprovider'),
        ),
        migrations.AddField(
            model_name='externalauthor',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.externalprovider'),
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('handle', models.CharField(blank=True, max_length=100)),
                ('access_token', apps.core.encryption.EncryptedTextField(blank=True)),
                ('refresh_token', apps.core.encryption.EncryptedTextField(blank=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='integrations.externalprovider')),
            ],
            options={
                'db_table': 'integrations_account',
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=40)),
                ('cursor', models.CharField(blank=True, max_length=300)),
                ('etag', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('idle', 'Au repos'), ('running', 'En cours'), ('error', 'Erreur')], default='idle', max_length=8)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('rate_limit_reset_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='integrations.externalaccount')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='integrations.externalprovider')),
            ],
            options={
                'db_table': 'integrations_sync_state',
            },
        ),
        migrations.AddIndex(
            model_name='externalcontent',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['expires_at'], name='extcontent_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontent',
            index=models.Index(fields=['provider', 'kind', '-published_at'], name='extcontent_browse_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalcontent',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_extcontent'),
        ),
        migrations.AddConstraint(
            model_name='externalauthor',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_extauthor'),
        ),
        migrations.AddConstraint(
            model_name='externalaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_extaccount_identity'),
        ),
        migrations.AddConstraint(
            model_name='externalaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'provider'), name='uniq_extaccount_user_active'),
        ),
        migrations.AddIndex(
            model_name='syncstate',
            index=models.Index(condition=models.Q(('status', 'running'), _negated=True), fields=['next_sync_at'], name='syncstate_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncstate',
            constraint=models.UniqueConstraint(fields=('provider', 'account', 'resource'), name='uniq_syncstate', nulls_distinct=False),
        ),
    ]
