# Generated by Django 5.2.18 on 2026-10-07 18:55

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe')], max_length=8)),
                ('value', models.PositiveIntegerField()),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('min_subtotal_minor', models.PositiveIntegerField(default=0)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('per_user_limit', models.PositiveSmallIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0, editable=False)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marketplace_coupon',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=24, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payee'), ('cancelled', 'Annulee'), ('partially_refunded', 'Partiellement remboursee'), ('refunded', 'Remboursee')], default='pending', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_minor', models.PositiveBigIntegerField()),
                ('discount_minor', models.PositiveBigIntegerField(default=0)),
                ('total_minor', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_order',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='marketplace.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='marketplace.order')),
            ],
            options={
                'db_table': 'marketplace_coupon_redemption',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('application', 'Application'), ('software', 'Logiciel'), ('service', 'Service'), ('template', 'Template'), ('resource', 'Ressource'), ('course', 'Formation'), ('digital_content', 'Contenu numerique')], max_length=16)),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=20000)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('suspended', 'Suspendu (moderation)'), ('archived', 'Archive')], default='draft', max_length=10)),
                ('license_type', models.CharField(choices=[('personal', 'Personnelle'), ('team', 'Equipe'), ('commercial', 'Commerciale'), ('none', 'Sans licence (service/formation)')], default='personal', max_length=10)),
                ('documentation_url', models.URLField(blank=True)),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False)),
                ('rating_sum', models.PositiveIntegerField(default=0, editable=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('skills', models.ManyToManyField(blank=True, db_table='marketplace_product_skill', related_name='products', to='profiles.skill')),
            ],
            options={
                'db_table': 'marketplace_product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('sku', models.CharField(max_length=60)),
                ('unit_price_minor', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('line_total_minor', models.PositiveBigIntegerField()),
                ('discount_minor', models.PositiveBigIntegerField(default=0)),
                ('platform_fee_minor', models.PositiveBigIntegerField(default=0)),
                ('seller_net_minor', models.PositiveBigIntegerField(default=0)),
                ('refunded_minor', models.PositiveBigIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='marketplace.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_order_item',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40, unique=True)),
                ('seats', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoquee')], default='active', max_length=8)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='license', to='marketplace.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_license',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.productcategory')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'db_table': 'marketplace_category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductEntitlementTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=10)),
                ('target_id', models.UUIDField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_targets', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_entitlement_target',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='image', max_length=10)),
                ('storage_key', models.CharField(max_length=400)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_product_media',
            },
        ),
        migrations.CreateModel(
            name='ProductRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40)),
                ('platform', models.CharField(default='any', max_length=20)),
                ('changelog', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('installation_instructions', models.TextField(blank=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_release',
            },
        ),
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=400)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='marketplace.productrelease')),
            ],
            options={
                'db_table': 'marketplace_digital_asset',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketplace.product')),
            ],
            options={
                'db_table': 'marketplace_variant',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.productvariant'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketplace.productvariant')),
            ],
            options={
                'db_table': 'marketplace_cart_item',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='marketplace.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_review',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspendue')], default='active', max_length=10)),
                ('company_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_store',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.store'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.store'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='marketplace.store'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketplace.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_wishlist',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='marketplace.digitalasset')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='marketplace.license')),
            ],
            options={
                'db_table': 'marketplace_download',
                'indexes': [models.Index(fields=['license', '-created_at'], name='download_license_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['created_at'], name='order_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_minor', django.db.models.expressions.CombinedExpression(models.F('subtotal_minor'), '-', models.F('discount_minor'))), ('discount_minor__lte', models.F('subtotal_minor'))), name='chk_order_totals'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='chk_order_paid_dated'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='uniq_order_idempotency'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'user'], name='redemption_user_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['user', 'product'], name='license_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='productentitlementtarget',
            constraint=models.UniqueConstraint(fields=('product', 'scope', 'target_id'), name='uniq_entitlement_target'),
        ),
        migrations.AddConstraint(
            model_name='productentitlementtarget',
            constraint=models.CheckConstraint(condition=models.Q(('scope__in', ['classroom', 'course', 'module', 'chapter'])), name='chk_target_scope'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(fields=('product', 'position'), name='uniq_productmedia_position'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.UniqueConstraint(fields=('product', 'version', 'platform'), name='uniq_release'),
        ),
        migrations.AddConstraint(
            model_name='productrelease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('product', 'platform'), name='uniq_release_latest'),
        ),
        migrations.AddConstraint(
            model_name='digitalasset',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='chk_asset_size'),
        ),
        migrations.AddConstraint(
            model_name='digitalasset',
            constraint=models.CheckConstraint(condition=models.Q(('checksum_sha256__regex', '^[0-9a-f]{64}$')), name='chk_asset_checksum'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='chk_variant_currency'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock__isnull', True), ('stock__gte', 0), _connector='OR'), name='chk_variant_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='uniq_variant_default'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'variant'), name='uniq_cartitem'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 100)), name='chk_cartitem_qty'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', '-created_at'], name='review_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='uniq_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='chk_review_rating'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['category', '-published_at'], name='product_browse_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'status'], name='product_store_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='uniq_product_slug'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_product_published_dated'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('rating_sum__lte', django.db.models.expressions.CombinedExpression(models.F('rating_count'), '*', models.Value(5)))), name='chk_product_rating_bounds'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['store', '-order_id'], name='orderitem_store_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orderitem_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total_minor', django.db.models.expressions.CombinedExpression(models.F('unit_price_minor'), '*', models.F('quantity')))), name='chk_item_line_total'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_minor__lte', models.F('line_total_minor'))), name='chk_item_discount'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee_minor__lte', django.db.models.expressions.CombinedExpression(models.F('line_total_minor'), '-', models.F('discount_minor'))), ('seller_net_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('line_total_minor'), '-', models.F('discount_minor')), '-', models.F('platform_fee_minor')))), name='chk_item_split'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_minor__lte', django.db.models.expressions.CombinedExpression(models.F('line_total_minor'), '-', models.F('discount_minor')))), name='chk_item_refund_cap'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='uniq_coupon_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'percent'), ('value__gte', 1), ('value__lte', 100)), models.Q(('kind', 'fixed'), ('value__gt', 0), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='chk_coupon_value'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='chk_coupon_period'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('max_redemptions__isnull', True), ('used_count__lte', models.F('max_redemptions')), _connector='OR'), name='chk_coupon_usage'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_wishlist'),
        ),
    ]
