# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.utils.timezone
import uuid
from django.contrib.postgres.operations import BtreeGistExtension, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGistExtension(),  # contraintes d'exclusion (periodes de sanctions sans chevauchement)
        TrigramExtension(),  # gin_trgm_ops (recherche floue profils/skills/hashtags)
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=60)),
                ('key', models.CharField(max_length=200)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('started', 'En cours'), ('completed', 'Termine'), ('failed', 'Echec')], default='started', max_length=10)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_idempotency_record',
                'indexes': [models.Index(fields=['expires_at'], name='idem_expires_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='uniq_idem_scope_key')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=60)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traite'), ('failed', 'Echec')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_outbox_event',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['available_at', 'id'], name='outbox_pending_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_aggregate_idx')],
            },
        ),
    ]
