# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(max_length=40)),
                ('subject_id', models.UUIDField()),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_review', 'En cours'), ('resolved', 'Resolu'), ('dismissed', 'Classe sans suite')], default='open', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=500)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_case',
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('warning', 'Avertissement'), ('hide', 'Masquer'), ('remove', 'Supprimer'), ('suspend', 'Suspendre'), ('ban', 'Bannir'), ('restore', 'Restaurer'), ('dismiss', 'Classer sans suite')], max_length=10)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.UUIDField()),
                ('reason', models.CharField(max_length=1000)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='moderation.moderationcase')),
            ],
            options={
                'db_table': 'moderation_action',
            },
        ),
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'moderation_report_reason',
                'constraints': [models.CheckConstraint(condition=models.Q(('severity__gte', 1), ('severity__lte', 5)), name='chk_reason_severity')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.UUIDField()),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('actioned', 'Traite (action prise)'), ('dismissed', 'Rejete')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='moderation.moderationcase')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='moderation.reportreason')),
            ],
            options={
                'db_table': 'moderation_report',
            },
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('warning', 'Avertissement'), ('posting_ban', 'Interdiction de publier'), ('messaging_ban', 'Interdiction de messagerie'), ('suspension', 'Suspension'), ('ban', 'Bannissement')], max_length=14)),
                ('reason', models.CharField(max_length=1000)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions', to='moderation.moderationaction')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_restriction',
            },
        ),
        migrations.CreateModel(
            name='ContentViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_code', models.CharField(max_length=40)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='moderation.moderationaction')),
            ],
            options={
                'db_table': 'moderation_violation',
                'indexes': [models.Index(fields=['user', '-created_at'], name='violation_user_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(condition=models.Q(('status__in', ['open', 'in_review'])), fields=['-priority', 'opened_at'], name='case_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['assignee', 'status'], name='case_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='moderationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'in_review'])), fields=('subject_type', 'subject_id'), name='uniq_case_open_subject'),
        ),
        migrations.AddConstraint(
            model_name='moderationcase',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['resolved', 'dismissed']), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='chk_case_resolved_dated'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='modaction_target_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator', '-created_at'], name='modaction_moderator_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['target_type', 'target_id'], name='report_target_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['status', 'created_at'], name='report_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'target_type', 'target_id'), name='uniq_report_open_per_reporter'),
        ),
        migrations.AddIndex(
            model_name='userrestriction',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user', 'kind'], name='restriction_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='userrestriction',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='chk_restriction_period'),
        ),
    ]
