# Generated by Django 5.2.18 on 2026-10-07 17:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('max_points', models.PositiveSmallIntegerField(default=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('allow_late', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('is_group', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'assessments_assignment',
            },
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'assessments_assignment_group',
            },
        ),
        migrations.CreateModel(
            name='AssignmentGroupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assessments_assignment_group_member',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('submitted', 'Rendu'), ('graded', 'Note')], default='submitted', max_length=10)),
                ('text', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_late', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'assessments_submission',
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected', models.JSONField(blank=True, default=list)),
                ('text', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'db_table': 'assessments_attempt_answer',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('correct_order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessments_choice',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'assessments_feedback',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'assessments_grade',
            },
        ),
        migrations.CreateModel(
            name='GradeCriterion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'assessments_grade_criterion',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiple'), ('true_false', 'Vrai/Faux'), ('text', 'Texte (reponse exacte normalisee)'), ('code', 'Code (correction manuelle)'), ('ordering', 'Mise en ordre')], max_length=10)),
                ('prompt', models.TextField()),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('explanation', models.TextField(blank=True)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'assessments_question',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('pass_percent', models.PositiveSmallIntegerField(default=60)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'db_table': 'assessments_quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('graded', 'Corrige'), ('pending_review', 'En attente de correction manuelle')], default='in_progress', max_length=14)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('passed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'assessments_quiz_attempt',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('max_points', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'assessments_rubric_criterion',
            },
        ),
    ]
