# Generated by Django 5.2.18 on 2026-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_initial"),
        ("education", "0002_links_and_repos"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="auto_grade",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="grading_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="reference_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="ai_error",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="ai_status",
            field=models.CharField(default="none", max_length=8),
        ),
        migrations.AddField(
            model_name="grade",
            name="ai_confidence",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="ai_model",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="grade",
            name="source",
            field=models.CharField(default="teacher", max_length=7),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("auto_grade", False),
                    models.Q(("reference_answer", ""), _negated=True),
                    _connector="OR",
                ),
                name="chk_assignment_autograde_ref",
            ),
        ),
    ]
