# Generated by Django 5.2.18 on 2026-10-07 18:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Carte'), ('manual', 'Manuel (virement, test)')], max_length=14)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initie'), ('succeeded', 'Reussi'), ('failed', 'Echoue'), ('cancelled', 'Annule'), ('refunded', 'Rembourse')], default='initiated', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='marketplace.order')),
            ],
            options={
                'db_table': 'payments_payment',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('requested', 'Demande'), ('processed', 'Effectue'), ('rejected', 'Refuse')], default='requested', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_decided', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='marketplace.orderitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_refund',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=14)),
                ('event_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payments_webhook_event',
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_webhook_event')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch', models.UUIDField(default=uuid.uuid4)),
                ('account', models.CharField(choices=[('buyer', 'Acheteur'), ('seller', 'Vendeur'), ('platform', 'Plateforme')], max_length=8)),
                ('kind', models.CharField(choices=[('charge', 'Encaissement'), ('refund', 'Remboursement')], max_length=8)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='marketplace.order')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='marketplace.store')),
            ],
            options={
                'db_table': 'payments_ledger_entry',
                'indexes': [models.Index(fields=['batch'], name='ledger_batch_idx'), models.Index(condition=models.Q(('store__isnull', False)), fields=['store', '-created_at'], name='ledger_store_idx'), models.Index(fields=['order'], name='ledger_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor', 0), _negated=True), name='chk_ledger_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('account', 'seller'), ('store__isnull', False)), models.Q(('account', 'seller'), _negated=True), _connector='OR'), name='chk_ledger_seller_store')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', '-created_at'], name='payment_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='chk_payment_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_ref', ''), _negated=True), fields=('provider', 'provider_ref'), name='uniq_payment_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'succeeded')), fields=('order',), name='uniq_payment_one_success_per_order'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='chk_refund_amount'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'requested'), ('decided_at__isnull', False), _connector='OR'), name='chk_refund_decided_dated'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'requested')), fields=('order_item',), name='uniq_refund_open_per_item'),
        ),
    ]
