# Generated by Django 5.2.18 on 2026-10-07 19:11

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ad_preference', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('personalized_ads', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'advertising_user_preference',
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_ref', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertising_advertiser',
            },
        ),
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('balance_minor', models.BigIntegerField(default=0)),
                ('spend_remainder_micro', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('advertiser', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='advertising.advertiser')),
            ],
            options={
                'db_table': 'advertising_account',
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('custom_list', 'Liste personnalisee'), ('rule_based', 'Par regles')], default='custom_list', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='advertising.advertiser')),
            ],
            options={
                'db_table': 'advertising_audience',
            },
        ),
        migrations.CreateModel(
            name='AudienceMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default='advertiser_list', max_length=30)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='advertising.audience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertising_audience_membership',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('objective', models.CharField(choices=[('awareness', 'Notoriete'), ('traffic', 'Trafic'), ('conversions', 'Conversions')], default='traffic', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminee')], default='draft', max_length=10)),
                ('pause_reason', models.CharField(blank=True, max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('daily_budget_minor', models.PositiveBigIntegerField()),
                ('total_budget_minor', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertising.adaccount')),
            ],
            options={
                'db_table': 'advertising_campaign',
            },
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause')], default='active', max_length=8)),
                ('billing_model', models.CharField(choices=[('cpc', 'Au clic'), ('cpm', 'Aux 1000 impressions')], default='cpc', max_length=3)),
                ('bid_minor', models.PositiveIntegerField()),
                ('placements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), default=list, size=None)),
                ('frequency_cap_per_day', models.PositiveSmallIntegerField(default=3)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_sets', to='advertising.audience')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_sets', to='advertising.campaign')),
            ],
            options={
                'db_table': 'advertising_adset',
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=6)),
                ('headline', models.CharField(max_length=90)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('media_key', models.CharField(blank=True, max_length=400)),
                ('cta_label', models.CharField(blank=True, max_length=30)),
                ('destination_url', models.URLField(max_length=500)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='advertising.advertiser')),
            ],
            options={
                'db_table': 'advertising_creative',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En moderation'), ('active', 'Diffusee'), ('paused', 'En pause'), ('rejected', 'Refusee')], default='draft', max_length=14)),
                ('review_notes', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ad_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertising.adset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='advertising.creative')),
            ],
            options={
                'db_table': 'advertising_ad',
            },
        ),
        migrations.CreateModel(
            name='TargetingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=24)),
                ('operator', models.CharField(choices=[('in', 'Parmi (OU)'), ('all', 'Tous (ET)'), ('not_in', 'Aucun de (NON)')], default='in', max_length=6)),
                ('values', models.JSONField(default=list)),
                ('required', models.BooleanField(default=True)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('ad_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='advertising.adset')),
            ],
            options={
                'db_table': 'advertising_targeting_rule',
            },
        ),
        migrations.CreateModel(
            name='AdAccountTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('topup', 'Recharge'), ('spend', 'Depense'), ('refund', 'Remboursement')], max_length=8)),
                ('amount_minor', models.BigIntegerField()),
                ('balance_after_minor', models.BigIntegerField()),
                ('reference', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='advertising.adaccount')),
            ],
            options={
                'db_table': 'advertising_account_transaction',
                'indexes': [models.Index(fields=['account', '-created_at'], name='adtx_account_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'reference'), name='uniq_adtx_reference'), models.CheckConstraint(condition=models.Q(('amount_minor', 0), _negated=True), name='chk_adtx_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('amount_minor__lt', 0), ('kind', 'spend')), models.Q(models.Q(('kind', 'spend'), _negated=True), ('amount_minor__gt', 0)), _connector='OR'), name='chk_adtx_sign')],
            },
        ),
        migrations.CreateModel(
            name='AdSettlement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch', models.UUIDField()),
                ('day', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('spend_micro', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='advertising.advertisement')),
            ],
            options={
                'db_table': 'advertising_settlement',
                'indexes': [models.Index(fields=['ad', 'day'], name='settlement_ad_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'ad', 'day'), name='uniq_settlement'), models.CheckConstraint(condition=models.Q(('clicks__lte', models.F('impressions')), ('impressions', 0), _connector='OR'), name='chk_settlement_clicks')],
            },
        ),
        migrations.AddConstraint(
            model_name='advertiser',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_advertiser_name'),
        ),
        migrations.AddConstraint(
            model_name='adaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance_minor__gte', 0)), name='chk_adaccount_no_overdraft'),
        ),
        migrations.AddConstraint(
            model_name='adaccount',
            constraint=models.CheckConstraint(condition=models.Q(('currency', ''), _negated=True), name='chk_adaccount_currency'),
        ),
        migrations.AddConstraint(
            model_name='adaccount',
            constraint=models.CheckConstraint(condition=models.Q(('spend_remainder_micro__lt', 1000000)), name='chk_adaccount_remainder'),
        ),
        migrations.AddConstraint(
            model_name='audience',
            constraint=models.UniqueConstraint(fields=('advertiser', 'name'), name='uniq_audience_name'),
        ),
        migrations.AddIndex(
            model_name='audiencemembership',
            index=models.Index(fields=['user'], name='audmember_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiencemembership',
            constraint=models.UniqueConstraint(fields=('audience', 'user'), name='uniq_audience_member'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['starts_at'], name='campaign_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('daily_budget_minor__gt', 0), ('total_budget_minor__gte', models.F('daily_budget_minor'))), name='chk_campaign_budgets'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='chk_campaign_period'),
        ),
        migrations.AddConstraint(
            model_name='adset',
            constraint=models.CheckConstraint(condition=models.Q(('bid_minor__gt', 0)), name='chk_adset_bid'),
        ),
        migrations.AddConstraint(
            model_name='adset',
            constraint=models.CheckConstraint(condition=models.Q(('frequency_cap_per_day__gte', 1), ('frequency_cap_per_day__lte', 50)), name='chk_adset_freqcap'),
        ),
        migrations.AddConstraint(
            model_name='creative',
            constraint=models.CheckConstraint(condition=models.Q(('destination_url__startswith', 'https://')), name='chk_creative_https'),
        ),
        migrations.AddConstraint(
            model_name='creative',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'text'), models.Q(('media_key', ''), _negated=True), _connector='OR'), name='chk_creative_media'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['ad_set'], name='ad_live_idx'),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['active', 'rejected']), _negated=True), ('reviewed_at__isnull', False), _connector='OR'), name='chk_ad_reviewed'),
        ),
        migrations.AddConstraint(
            model_name='targetingrule',
            constraint=models.CheckConstraint(condition=models.Q(('field__in', ['interest', 'skill', 'technology', 'profession', 'country', 'region', 'language', 'level', 'domain', 'availability', 'followed_category', 'viewed_content_type'])), name='chk_targeting_field_allowed'),
        ),
        migrations.AddConstraint(
            model_name='targetingrule',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 1), ('weight__lte', 10)), name='chk_targeting_weight'),
        ),
    ]
