# Generated by Django 5.2.18 on 2026-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adsettlement',
            name='chk_settlement_clicks',
        ),
    ]
