# Generated by Django 5.2.18 on 2026-10-07 17:43

import django.db.models.constraints
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10)),
                ('is_free', models.BooleanField(default=True)),
                ('price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'education_chapter',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('privacy', models.CharField(choices=[('public', 'Publique'), ('private', 'Privee (adhesion sur approbation)'), ('invite_only', 'Sur invitation'), ('organization', 'Reservee a une organisation')], default='public', max_length=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('organization_ref', models.UUIDField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='community.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_classroom',
            },
        ),
        migrations.CreateModel(
            name='ClassroomInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietaire'), ('instructor', 'Enseignant'), ('assistant', 'Assistant'), ('student', 'Etudiant')], default='student', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('declined', 'Refusee'), ('revoked', 'Revoquee')], default='pending', max_length=9)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='education.classroom')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_classroom_invitation',
            },
        ),
        migrations.CreateModel(
            name='ClassroomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietaire'), ('instructor', 'Enseignant'), ('assistant', 'Assistant'), ('student', 'Etudiant')], default='student', max_length=10)),
                ('status', models.CharField(choices=[('pending', "En attente d'approbation"), ('active', 'Actif'), ('banned', 'Banni')], default='active', max_length=8)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='education.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_classroom_member',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('text', 'Texte'), ('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('code', 'Code'), ('notebook', 'Notebook'), ('presentation', 'Presentation'), ('document', 'Document'), ('link', 'Lien'), ('embed', 'Embed'), ('quiz', 'Quiz'), ('exercise', 'Exercice')], max_length=12)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField(blank=True)),
                ('storage_key', models.CharField(blank=True, max_length=400)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='education.chapter')),
            ],
            options={
                'db_table': 'education_content_block',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('level', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance')], default='beginner', max_length=14)),
                ('language', models.CharField(default='fr', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('archived', 'Archive')], default='draft', max_length=10)),
                ('is_free', models.BooleanField(default=True)),
                ('price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('certificate_enabled', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='education.classroom')),
                ('skills', models.ManyToManyField(blank=True, db_table='education_course_skill', related_name='courses', to='profiles.skill')),
            ],
            options={
                'db_table': 'education_course',
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Enseignant principal'), ('assistant', 'Co-enseignant')], default='assistant', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='education.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_course_instructor',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Inscrit'), ('completed', 'Termine'), ('dropped', 'Abandonne')], default='active', max_length=10)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('is_free', models.BooleanField(default=True)),
                ('price_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='education.course')),
            ],
            options={
                'db_table': 'education_module',
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('classroom', 'Classroom'), ('course', 'Cours'), ('module', 'Module'), ('chapter', 'Chapitre')], max_length=10)),
                ('source', models.CharField(choices=[('purchase', 'Achat'), ('grant', 'Offert'), ('subscription', 'Abonnement'), ('instructor', 'Enseignant')], max_length=12)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('grant_key', models.CharField(blank=True, max_length=200)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='education.chapter')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='education.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='education.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='education.module')),
            ],
            options={
                'db_table': 'education_entitlement',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='education.module'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(condition=models.Q(('archived_at__isnull', True)), fields=['privacy', '-created_at'], name='classroom_discover_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_paid', False), ('price_minor__isnull', True)), models.Q(('is_paid', True), ('price_minor__gt', 0), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='chk_classroom_pricing'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('privacy', 'organization'), _negated=True), ('organization_ref__isnull', False), _connector='OR'), name='chk_classroom_org_ref'),
        ),
        migrations.AddConstraint(
            model_name='classroominvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('classroom', 'invited_user'), name='uniq_classinvite_pending'),
        ),
        migrations.AddIndex(
            model_name='classroommember',
            index=models.Index(fields=['user', 'status'], name='classmember_user_idx'),
        ),
        migrations.AddIndex(
            model_name='classroommember',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['classroom', '-joined_at'], name='classmember_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroommember',
            constraint=models.UniqueConstraint(fields=('classroom', 'user'), name='uniq_classroom_member'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('chapter', 'position'), name='uniq_block_position'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['text', 'code']), _negated=True), models.Q(('body', ''), _negated=True), _connector='OR'), name='chk_block_text_body'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['pdf', 'image', 'audio', 'video', 'notebook', 'presentation', 'document']), _negated=True), models.Q(('storage_key', ''), _negated=True), models.Q(('url', ''), _negated=True), _connector='OR'), name='chk_block_file_source'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['link', 'embed']), _negated=True), ('url__startswith', 'https://'), _connector='OR'), name='chk_block_link_https'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['quiz', 'exercise']), _negated=True), ('ref_id__isnull', False), _connector='OR'), name='chk_block_ref'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['-published_at'], name='course_published_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['classroom', 'status'], name='course_classroom_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('classroom', 'slug'), name='uniq_course_slug'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_free', True), ('price_minor__isnull', True)), models.Q(('is_free', False), ('price_minor__gt', 0), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='chk_course_pricing'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_course_published_dated'),
        ),
        migrations.AddConstraint(
            model_name='courseinstructor',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='uniq_course_instructor'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', '-enrolled_at'], name='enrollment_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='uniq_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='chk_enrollment_completed_dated'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('course', 'position'), name='uniq_module_position'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_free', True), ('price_minor__isnull', True)), models.Q(('is_free', False), ('price_minor__gt', 0), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='chk_module_pricing'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user', 'scope'], name='entitlement_user_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(condition=models.Q(('chapter__isnull', False)), fields=['chapter'], name='entitlement_chapter_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(condition=models.Q(('module__isnull', False)), fields=['module'], name='entitlement_module_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(condition=models.Q(('course__isnull', False)), fields=['course'], name='entitlement_course_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chapter__isnull', True), ('classroom__isnull', False), ('course__isnull', True), ('module__isnull', True), ('scope', 'classroom')), models.Q(('chapter__isnull', True), ('classroom__isnull', True), ('course__isnull', False), ('module__isnull', True), ('scope', 'course')), models.Q(('chapter__isnull', True), ('classroom__isnull', True), ('course__isnull', True), ('module__isnull', False), ('scope', 'module')), models.Q(('chapter__isnull', False), ('classroom__isnull', True), ('course__isnull', True), ('module__isnull', True), ('scope', 'chapter')), _connector='OR'), name='chk_entitlement_single_target'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(condition=models.Q(('grant_key', ''), _negated=True), fields=('grant_key',), name='uniq_entitlement_grant_key'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('module', 'position'), name='uniq_chapter_position'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_free', True), ('price_minor__isnull', True)), models.Q(('is_free', False), ('price_minor__gt', 0), models.Q(('currency', ''), _negated=True)), _connector='OR'), name='chk_chapter_pricing'),
        ),
    ]
