# Generated by Django 5.2.18 on 2026-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Texte"),
                    ("pdf", "PDF"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("code", "Code"),
                    ("notebook", "Notebook"),
                    ("presentation", "Presentation"),
                    ("document", "Document"),
                    ("link", "Lien"),
                    ("embed", "Embed"),
                    ("quiz", "Quiz"),
                    ("exercise", "Exercice"),
                    ("repository", "Depot GitHub"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="contentblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "repository"), _negated=True),
                    ("url__startswith", "https://github.com/"),
                    _connector="OR",
                ),
                name="chk_block_repo_github",
            ),
        ),
    ]
