# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('actor_required', models.BooleanField(default=True)),
                ('contains_pii', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=400)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_event_type',
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('metric', models.CharField(max_length=60)),
                ('dimension', models.CharField(blank=True, default='', max_length=80)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'analytics_daily_metric',
                'indexes': [models.Index(fields=['metric', '-day'], name='dailymetric_metric_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'metric', 'dimension'), name='uniq_dailymetric'), models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='chk_dailymetric_nonneg')],
            },
        ),
    ]
