# Generated by Django 5.2.18 on 2026-10-07 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('issuer', models.CharField(blank=True, max_length=140)),
                ('achieved_on', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_achievement',
            },
        ),
        migrations.CreateModel(
            name='CertificateEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('issuer', models.CharField(blank=True, max_length=140)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('platform_certificate_ref', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_certificate_entry',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='portfolio', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('summary', models.TextField(blank=True, max_length=3000)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='public', max_length=14)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'portfolio_portfolio',
                'constraints': [models.CheckConstraint(condition=models.Q(('visibility__in', ['group_members', 'custom']), _negated=True), name='chk_portfolio_visibility')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.portfolio')),
                ('technologies', models.ManyToManyField(blank=True, db_table='portfolio_project_technology', related_name='portfolio_projects', to='profiles.skill')),
            ],
            options={
                'db_table': 'portfolio_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('demo', 'Demo'), ('repository', 'Depot'), ('article', 'Article'), ('other', 'Autre')], default='other', max_length=12)),
                ('provider', models.CharField(blank=True, max_length=12)),
                ('url', models.URLField(max_length=400)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.project')),
            ],
            options={
                'db_table': 'portfolio_project_link',
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='image', max_length=10)),
                ('storage_key', models.CharField(max_length=400)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portfolio.project')),
            ],
            options={
                'db_table': 'portfolio_project_media',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=8)),
                ('full_name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=400)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(blank=True, max_length=40)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='portfolio.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_repository',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=160)),
                ('degree', models.CharField(blank=True, max_length=140)),
                ('field', models.CharField(blank=True, max_length=140)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_education',
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('started_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='chk_education_dates')],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=140)),
                ('company_ref', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=140)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_experience',
                'indexes': [models.Index(fields=['user', '-started_on'], name='experience_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='chk_experience_dates')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['portfolio', 'position'], name='project_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('portfolio', 'slug'), name='uniq_project_slug'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('started_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='chk_project_dates'),
        ),
        migrations.AddConstraint(
            model_name='projectlink',
            constraint=models.CheckConstraint(condition=models.Q(('url__startswith', 'https://')), name='chk_projectlink_https'),
        ),
        migrations.AddConstraint(
            model_name='projectlink',
            constraint=models.UniqueConstraint(fields=('project', 'url'), name='uniq_projectlink'),
        ),
        migrations.AddConstraint(
            model_name='projectmedia',
            constraint=models.UniqueConstraint(fields=('project', 'position'), name='uniq_projectmedia_position'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'full_name'), name='uniq_repository'),
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['github', 'gitlab'])), name='chk_repository_provider'),
        ),
    ]
