# Generated by Django 5.2.18 on 2026-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="owner_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repository",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
