# Generated by Django 5.2.18 on 2026-10-08 01:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=24)),
                ('key', models.CharField(max_length=500, unique=True)),
                ('filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Envoi en attente'), ('uploaded', 'Envoye et verifie'), ('deleted', 'Supprime')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storage_file',
                'indexes': [models.Index(fields=['owner', '-created_at'], name='file_owner_idx'), models.Index(condition=models.Q(('status', 'pending')), fields=['created_at'], name='file_pending_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='chk_file_size'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'uploaded'), _negated=True), ('uploaded_at__isnull', False), _connector='OR'), name='chk_file_uploaded_dated')],
            },
        ),
    ]
