# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends_block',
                'indexes': [models.Index(fields=['blocked'], name='block_blocked_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='uniq_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='chk_block_not_self')],
            },
        ),
        migrations.CreateModel(
            name='CloseFriend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends_close_friend',
                'indexes': [models.Index(fields=['friend'], name='closefriend_friend_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'friend'), name='uniq_closefriend'), models.CheckConstraint(condition=models.Q(('owner', models.F('friend')), _negated=True), name='chk_closefriend_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends_follow',
                'indexes': [models.Index(fields=['followee', '-created_at'], name='follow_followee_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'followee'), name='uniq_follow'), models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='chk_follow_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('declined', 'Refusee'), ('cancelled', 'Annulee')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends_friendship',
                'indexes': [models.Index(condition=models.Q(('status', 'accepted')), fields=['user_low', 'user_high'], name='friend_low_acc_idx'), models.Index(condition=models.Q(('status', 'accepted')), fields=['user_high', 'user_low'], name='friend_high_acc_idx'), models.Index(condition=models.Q(('status', 'pending')), fields=['user_low', '-created_at'], name='friend_low_pend_idx'), models.Index(condition=models.Q(('status', 'pending')), fields=['user_high', '-created_at'], name='friend_high_pend_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user_low__lt', models.F('user_high'))), name='chk_friendship_ordered'), models.CheckConstraint(condition=models.Q(('requested_by', models.F('user_low')), ('requested_by', models.F('user_high')), _connector='OR'), name='chk_friendship_requester_in_pair'), models.UniqueConstraint(fields=('user_low', 'user_high'), name='uniq_friendship_pair')],
            },
        ),
        migrations.CreateModel(
            name='Mute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('posts', 'Publications'), ('status', 'Statuts'), ('notifications', 'Notifications'), ('all', 'Tout')], default='all', max_length=14)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends_mute',
                'constraints': [models.UniqueConstraint(fields=('muter', 'muted', 'scope'), name='uniq_mute'), models.CheckConstraint(condition=models.Q(('muter', models.F('muted')), _negated=True), name='chk_mute_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('restricted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restrictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends_restriction',
                'constraints': [models.UniqueConstraint(fields=('restrictor', 'restricted'), name='uniq_restriction'), models.CheckConstraint(condition=models.Q(('restrictor', models.F('restricted')), _negated=True), name='chk_restriction_not_self')],
            },
        ),
    ]
