# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('code', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'community_group_permission',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('privacy', models.CharField(choices=[('public', 'Publique'), ('private', 'Privee')], default='public', max_length=10)),
                ('avatar_key', models.CharField(blank=True, max_length=300)),
                ('cover_key', models.CharField(blank=True, max_length=300)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'db_table': 'community_community',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('privacy', models.CharField(choices=[('public', 'Public (visible, lisible par tous)'), ('private', 'Prive (visible, contenu reserve aux membres)'), ('hidden', 'Secret (invisible hors membres)')], default='public', max_length=10)),
                ('join_policy', models.CharField(choices=[('open', 'Ouvert'), ('approval', 'Sur approbation'), ('invite_only', 'Sur invitation')], default='open', max_length=12)),
                ('avatar_key', models.CharField(blank=True, max_length=300)),
                ('cover_key', models.CharField(blank=True, max_length=300)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='community.community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_group',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classroom_ref', models.UUIDField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Prive'), ('restricted', 'Restreint (lecture seule sauf roles)'), ('announcement', 'Annonces'), ('discussion', 'Discussion'), ('support', 'Support'), ('classroom', 'Lie a une classroom')], default='discussion', max_length=14)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='community.community')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='community.group')),
            ],
            options={
                'db_table': 'community_channel',
            },
        ),
        migrations.CreateModel(
            name='GroupBan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='community.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_group_ban',
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('declined', 'Refusee'), ('revoked', 'Revoquee'), ('expired', 'Expiree')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='community.group')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_group_invitation',
            },
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvee'), ('rejected', 'Rejetee'), ('cancelled', 'Annulee')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='community.group')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_group_join_request',
            },
        ),
        migrations.CreateModel(
            name='GroupMute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='community.group')),
                ('muted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_group_mute',
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_owner_role', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='community.group')),
                ('permissions', models.ManyToManyField(blank=True, db_table='community_group_role_permission', related_name='roles', to='community.grouppermission')),
            ],
            options={
                'db_table': 'community_group_role',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.group')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='community.grouprole')),
            ],
            options={
                'db_table': 'community_group_member',
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Membre'), ('moderator', 'Moderateur')], default='member', max_length=10)),
                ('notifications_muted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_channel_member',
                'indexes': [models.Index(fields=['user'], name='channelmember_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'user'), name='uniq_channel_member')],
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(condition=models.Q(('archived_at__isnull', True)), fields=['privacy', '-created_at'], name='community_priv_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['community', '-member_count'], name='group_community_size_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(condition=models.Q(('archived_at__isnull', True), ('privacy', 'public')), fields=['-member_count'], name='group_discover_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(condition=models.Q(('classroom_ref__isnull', False)), fields=['classroom_ref'], name='channel_classroom_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('community__isnull', True), ('group__isnull', False)), models.Q(('community__isnull', False), ('group__isnull', True)), models.Q(('classroom_ref__isnull', False), ('community__isnull', True), ('group__isnull', True)), _connector='OR'), name='chk_channel_single_parent'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('group', 'slug'), name='uniq_channel_group_slug'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(condition=models.Q(('community__isnull', False)), fields=('community', 'slug'), name='uniq_channel_comm_slug'),
        ),
        migrations.AddConstraint(
            model_name='groupban',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_ban'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['invited_user', '-created_at'], name='groupinvite_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('group', 'invited_user'), name='uniq_group_invite_pending'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['group', '-created_at'], name='groupjoinreq_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('group', 'user'), name='uniq_group_joinreq_pending'),
        ),
        migrations.AddConstraint(
            model_name='groupmute',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_mute'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='uniq_grouprole_name'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('group',), name='uniq_grouprole_default'),
        ),
        migrations.AddConstraint(
            model_name='grouprole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner_role', True)), fields=('group',), name='uniq_grouprole_owner'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user', '-joined_at'], name='groupmember_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uniq_group_member'),
        ),
    ]
