# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Video'), ('link', 'Lien'), ('code', 'Code'), ('repository', 'Depot (GitHub/GitLab)'), ('project', 'Projet'), ('portfolio', 'Portfolio'), ('event', 'Evenement'), ('job', "Offre d'emploi"), ('course', 'Formation'), ('poll', 'Sondage'), ('external', 'Contenu externe (embed officiel)')], default='text', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie'), ('pending_review', 'En moderation'), ('hidden', 'Masque par la moderation'), ('removed', 'Retire')], default='published', max_length=14)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True, max_length=20000)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='public', max_length=14)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ref_type', models.CharField(blank=True, max_length=30)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('reaction_count', models.PositiveIntegerField(default=0, editable=False)),
                ('comment_count', models.PositiveIntegerField(default=0, editable=False)),
                ('share_count', models.PositiveIntegerField(default=0, editable=False)),
                ('save_count', models.PositiveIntegerField(default=0, editable=False)),
                ('view_count', models.PositiveBigIntegerField(default=0, editable=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.community')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.group')),
            ],
            options={
                'db_table': 'social_post',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'db_table': 'social_poll_option',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=255)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField(max_length=5000)),
                ('reaction_count', models.PositiveIntegerField(default=0, editable=False)),
                ('reply_count', models.PositiveIntegerField(default=0, editable=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.post')),
            ],
            options={
                'db_table': 'social_comment',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=60, unique=True)),
                ('post_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'db_table': 'social_hashtag',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tag'], name='hashtag_trgm', opclasses=['gin_trgm_ops']), models.Index(fields=['-post_count'], name='hashtag_popular_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tag', django.db.models.functions.text.Lower('tag'))), name='chk_hashtag_lower')],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='poll', serialize=False, to='social.post')),
                ('question', models.CharField(max_length=300)),
                ('allows_multiple', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_poll',
            },
        ),
        migrations.CreateModel(
            name='PostAudience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_post_audience',
            },
        ),
        migrations.CreateModel(
            name='PostEditHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_title', models.CharField(blank=True, max_length=200)),
                ('previous_body', models.TextField(blank=True)),
                ('previous_payload', models.JSONField(blank=True, default=dict)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='social.post')),
            ],
            options={
                'db_table': 'social_post_edit_history',
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='social.hashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='social.post')),
            ],
            options={
                'db_table': 'social_post_hashtag',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=10)),
                ('storage_key', models.CharField(max_length=400)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='social.post')),
            ],
            options={
                'db_table': 'social_post_media',
            },
        ),
        migrations.CreateModel(
            name='PostMention',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_post_mention',
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('like', "J'aime"), ('love', "J'adore"), ('celebrate', 'Bravo'), ('insightful', 'Instructif'), ('funny', 'Drole'), ('support', 'Soutien')], default='like', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_post_reaction',
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collection', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_save',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='public', max_length=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_share',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'Lien'), ('document', 'Document')], default='text', max_length=10)),
                ('body', models.CharField(blank=True, max_length=700)),
                ('storage_key', models.CharField(blank=True, max_length=400)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Abonnes'), ('friends', 'Amis'), ('close_friends', 'Amis proches'), ('group_members', 'Membres du groupe'), ('custom', 'Audience personnalisee'), ('private', 'Moi uniquement')], default='friends', max_length=14)),
                ('expires_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'db_table': 'social_status',
            },
        ),
        migrations.CreateModel(
            name='StatusAudience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='social.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_status_audience',
            },
        ),
        migrations.CreateModel(
            name='StatusReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_status_reaction',
            },
        ),
        migrations.CreateModel(
            name='StatusReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=1000)),
                ('message_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.status')),
            ],
            options={
                'db_table': 'social_status_reply',
            },
        ),
        migrations.CreateModel(
            name='StatusView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='social.status')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_status_view',
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('like', "J'aime"), ('love', "J'adore"), ('celebrate', 'Bravo'), ('insightful', 'Instructif'), ('funny', 'Drole'), ('support', 'Soutien')], default='like', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_comment_reaction',
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='uniq_comment_reaction')],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.polloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.poll')),
            ],
            options={
                'db_table': 'social_poll_vote',
            },
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='social.poll'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'published')), fields=['author', '-published_at'], name='post_author_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('group__isnull', False), ('status', 'published')), fields=['group', '-published_at'], name='post_group_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'published'), ('visibility', 'public')), fields=['-published_at'], name='post_public_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'published')), fields=['kind', '-published_at'], name='post_kind_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='post_payload_gin', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('ref_id__isnull', False)), fields=['ref_type', 'ref_id'], name='post_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('visibility', 'group_members'), _negated=True), ('group__isnull', False), _connector='OR'), name='chk_post_group_visibility'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ref_id__isnull', True), ('ref_type', '')), models.Q(models.Q(('ref_type', ''), _negated=True), ('ref_id__isnull', False)), _connector='OR'), name='chk_post_ref_pair'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['text']), _negated=True), models.Q(('body', ''), _negated=True), _connector='OR'), name='chk_post_text_has_body'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=['post', 'created_at', 'id'], name='comment_post_root_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(condition=models.Q(('parent__isnull', False)), fields=['parent', 'created_at', 'id'], name='comment_replies_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='comment_author_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('depth__lte', 2)), name='chk_comment_depth'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('depth', 0), ('parent__isnull', True)), models.Q(('depth__gt', 0), ('parent__isnull', False)), _connector='OR'), name='chk_comment_parent_depth'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='chk_comment_body'),
        ),
        migrations.AddIndex(
            model_name='postaudience',
            index=models.Index(fields=['user', 'post'], name='postaudience_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='postaudience',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_audience'),
        ),
        migrations.AddIndex(
            model_name='postedithistory',
            index=models.Index(fields=['post', '-edited_at'], name='postedit_post_idx'),
        ),
        migrations.AddIndex(
            model_name='posthashtag',
            index=models.Index(fields=['hashtag', '-post_id'], name='posthashtag_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.UniqueConstraint(fields=('post', 'hashtag'), name='uniq_post_hashtag'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.UniqueConstraint(fields=('post', 'position'), name='uniq_postmedia_position'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='chk_postmedia_size'),
        ),
        migrations.AddIndex(
            model_name='postmention',
            index=models.Index(fields=['user'], name='postmention_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmention',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_mention'),
        ),
        migrations.AddIndex(
            model_name='postreaction',
            index=models.Index(fields=['user', '-created_at'], name='postreaction_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_post_reaction'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['user', '-created_at'], name='save_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='save',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_save'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['post', '-created_at'], name='share_post_idx'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uniq_share'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['author', '-created_at'], name='status_author_idx'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(condition=models.Q(('archived_at__isnull', True), ('deleted_at__isnull', True)), fields=['expires_at'], name='status_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_status_expiry'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.CheckConstraint(condition=models.Q(('visibility', 'group_members'), _negated=True), name='chk_status_no_group_visibility'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('body__gt', ''), ('kind', 'text')), models.Q(('kind', 'text'), _negated=True), _connector='OR'), name='chk_status_text_body'),
        ),
        migrations.AddIndex(
            model_name='statusaudience',
            index=models.Index(fields=['user', 'status'], name='statusaud_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='statusaudience',
            constraint=models.UniqueConstraint(fields=('status', 'user'), name='uniq_status_audience'),
        ),
        migrations.AddConstraint(
            model_name='statusreaction',
            constraint=models.UniqueConstraint(fields=('status', 'user'), name='uniq_status_reaction'),
        ),
        migrations.AddIndex(
            model_name='statusreply',
            index=models.Index(fields=['status', 'created_at'], name='statusreply_status_idx'),
        ),
        migrations.AddIndex(
            model_name='statusview',
            index=models.Index(fields=['viewer', '-viewed_at'], name='statusview_viewer_idx'),
        ),
        migrations.AddConstraint(
            model_name='statusview',
            constraint=models.UniqueConstraint(fields=('status', 'viewer'), name='uniq_status_view'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'user'], name='pollvote_poll_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('option', 'user'), name='uniq_pollvote_option_user'),
        ),
        migrations.AddConstraint(
            model_name='polloption',
            constraint=models.UniqueConstraint(fields=('poll', 'position'), name='uniq_polloption_position'),
        ),
    ]
