# Generated by Django 5.2.18 on 2026-10-07 03:31

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('default_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('in_app', "Dans l'application"), ('websocket', 'Temps reel'), ('email', 'Email'), ('push', 'Push mobile/web'), ('telegram', 'Telegram')], max_length=10), default=list, size=None)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notifications_type',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='notifications.notificationtype')),
            ],
            options={
                'db_table': 'notifications_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', "Dans l'application"), ('websocket', 'Temps reel'), ('email', 'Email'), ('push', 'Push mobile/web'), ('telegram', 'Telegram')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoye'), ('failed', 'Echec'), ('skipped', 'Ignore (preferences)')], default='pending', max_length=8)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notifications_delivery',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['channel', 'created_at'], name='delivery_pending_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel'), name='uniq_delivery_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', "Dans l'application"), ('websocket', 'Temps reel'), ('email', 'Email'), ('push', 'Push mobile/web'), ('telegram', 'Telegram')], max_length=10)),
                ('language', models.CharField(default='fr', max_length=8)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationtype')),
            ],
            options={
                'db_table': 'notifications_template',
                'constraints': [models.UniqueConstraint(fields=('type', 'channel', 'language'), name='uniq_notif_template')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', "Dans l'application"), ('websocket', 'Temps reel'), ('email', 'Email'), ('push', 'Push mobile/web'), ('telegram', 'Telegram')], max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notifications.notificationtype')),
            ],
            options={
                'db_table': 'notifications_preference',
                'constraints': [models.UniqueConstraint(fields=('user', 'type', 'channel'), name='uniq_notif_pref', nulls_distinct=False)],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at', '-id'], name='notif_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('read_at__isnull', True)), fields=['recipient', '-created_at'], name='notif_unread_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'dedupe_key'), name='uniq_notification_dedupe'),
        ),
    ]
